name: Nuestro primer workflow en GitHub Actions
on:
  push:
    branches:
      - main
      - develop

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Eggnesto estuvo aqui."